# Generated by Django 4.0.6 on 2022-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_alter_mapastexto_texto_temas_alter_aulas_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='thumb',
            field=models.CharField(max_length=500),
        ),
    ]
